.TH GIPH 1 "April 2019" "MIT License" "User Commands"
.SH NAME
\fBgiph\fR \- record gif from desktop, window or selection
.SH SYNOPSIS
\fBgiph\fR [\fIOPTIONS\fR] [\fIFILENAME\fR]
.br
\fBgiph\fR
[\fB-g\fR \fIGEOMETRY\fR |
\fB-w\fR \fIINT\fR |
\fB-s\fR [\fB-l\fR] [\fB-c\fR \fIFLOAT,FLOAT,FLOAT,FLOAT\fR] [\fB-p\fR \fIFLOAT\fR] [\fB-b\fR \fIFLOAT\fR]]
[\fB-i\fR \fIINTERFACE\fR]
[\fB-e\fR \fIENCODER\fR [=\fIgifski\fR \fB-q\fR \fIINT\fR]]
[\fB-d\fR \fIINT\fR]
[\fB-t\fR \fIINT\fR]
[\fB-f\fR \fIINT\fR]
[\fIFILENAME\fR]
.SH DESCRIPTION
\fBgiph\fR is a screen recorder that records the desktop, a window or selection and encodes it into a gif file.
It prints the encoded gif directly to standard output when omitting [\fIFILENAME\fR].
.SH EXAMPLES
.TP
\fBgiph -g \fI300x200+600+200 ~/Videos/$(date +%s).png\fR
Records a 300x200 pixel (width x height) rectangle, that is shifted 600 pixel
to the right and 200 pixel down from the top-left corner.
The recording stops when either \fBctrl+c\fR is pressed, or the \fBprocess group is interrupted\fR.
The encoded gif will be saved in your users Videos directory and has the current timestamp as a name.
To send an interrupt signal to the process group, you can use:
.in +2
\(bu \fBkill -INT -\fIPID\fR
.br
\(bu \fBkillall -INT -g \fIgiph\fR
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print help and exit.
.TP
.BR \-\-version
Print version and exit.
.TP
.BR \-v* ", " \-\-verbose ", " \-\-quiet
Defines how verbose giph will be. Omitting [\fIFILENAME\fR] will overwrite the verbosity to \fI-1\fR (quiet).  Use the following list to determine which option to use for each verbosity level:
.in +2
\(bu \fI-1\fR (quiet) \fB--quiet\fR - logs errors
.br
\(bu  \fI0\fR (normal) - like quiet, also displays interactive components
.br
\(bu  \fI1\fR (verbose) \fB-v\fR, \fB--verbose\fR - like normal, also logs basic information about steps
.br
\(bu  \fI2\fR (very_verbose) \fB-vv\fR - like verbose, also logs detailed information about steps
.br
\(bu  \fI3\fR (debug) \sp2 \fB-vvv\fR - like very_verbose, also shows output of background processes
.TP
.BR \-s ", " \-\-select
Uses slop to interactively select the desired region or window to record.
This uses the \fBSLOP OPTIONS\fR described below.
.TP
.BR \-g ", " \-\-geometry " " \fIGEOMETRY\fR
Sets the region to capture.
.TP
.BR \-w ", " \-\-window " " \fIINT\fR
Sets the window id of the desired window to capture.
.TP
.BR \-i ", " \-\-interface " \fISTRING\fR (default: \fIcli\fR)"
Selects the user interface method that is used for countdown, timer and to stop the recording.
The possible values are:
.in +2
\(bu \fIcli\fR: uses the terminal as a user interface
.br
\(bu \fIzenity\fR: displays control-windows using zenity
.TP
.BR \-e ", " \-\-encoder " \fISTRING\fR (default: \fIffmpeg\fR)"
Selects one of the following encoders uses to encode the gif:
.in +2
\(bu \fIffmpeg\fR: high quality gif encoder
.br
\(bu \fIgifski\fR: highest quality gif encoder, rather slow, uses \fBGIFSKI OPTIONS\fR described below
.TP
.BR \-d ", " \-\-delay " " \fIINT\fR
Sets the time in seconds to wait before the recording starts.
.TP
.BR \-t ", " \-\-timer " " \fITIMEDURATION\fR
Sets a fixed time to record. The format is a timeduration as described in the ffmpeg documentation
(https://ffmpeg.org/ffmpeg-utils.html#Time-duration).
As an example, '10' would mean 10 seconds, '3:30' means 3 minutes and 30 seconds,
'1:02:03' means 1 hour, 2 minutes and 3 seconds, and '5.5' means 5.5 seconds.
.TP
.BR \-f ", " \-\-framerate " " \fIINT\fR
Sets the desired framerate of the recorded gif. A higher framerate will result in a larger filesize.
.SH SLOP OPTIONS
When \fB-s\fR or \fB--select\fR is used, slop will be used to get geometry information.
For a more detailed description of slops options, see \fBslop(1)\fR.
The following options will be passed to slop if they are set:
.TP
.BR \-b ", " \-\-bordersize " \fIFLOAT\fR (default: \fI1\fR)"
Set the selection border thickness.
.TP
.BR \-p ", " \-\-padding " \fIFLOAT\fR (default: \fI0\fR)"
Set the selection padding. This can be negative.
.TP
.BR \-t ", " \-\-tolerance " \fIFLOAT\fR (default: \fI2\fR)"
Defines how far the mouse can move after clicking while still being considered a click.
.TP
.BR \-c ", " \-\-color " \fIFLOAT,FLOAT,FLOAT,FLOAT\fR (default: \fI0.5,0.5,0.5,1\fR)"
Set the selection color as RGB or ARGB.
.TP
.BR \-r ", " \-\-shader
Set a shader to be used.
.TP
.BR \-n ", " \-\-nodecorations " \fIINT\fR (default: \fI0\fR)"
Tries to select child windows. \fI0\fR is off, \fI1\fR tries to remove decorations,
\fI2\fR aggressively tries to remove decorations.
.TP
.BR \-l ", " \-\-highlight
Highlight the selection rectangle. This uses the color provided in \fB-c\fR or \fB--color\fR.
.TP
.BR \-k ", " \-\-nokeyboard
Disable being able to cancel the selection using the keyboard.
.TP
.BR \-o ", " \-\-noopengl
Disable graphics acceleration.
.SH GIFSKI OPTIONS
When \fB-e\fR or \fB--encoder\fR \fIgifski\fR is used, gifski will be used as the gif encoder.
The following options will be passed to gifski if they are set: 
.TP
.BR \-q ", " \-\-quality " \fIINT\fR (default: \fI80\fR)"
Set the quality from 1 to 100, where 1 is the lowest, and 100 the best quality.
.TP
.BR \-f ", " \-\-fast
Makes the encoding 3 times faster. Results in 10% lower quality and a bigger filesize though.
.SH SEE ALSO
.BR slop(1)